site_name: Pyllot
repo_url: https://github.com/tom-bartk/pyllot

theme:
  name: material
  icon:
    logo: material/navigation-variant

  palette:
    scheme: gruvbox
  font: false

nav:
  - Overview: "index.md"
  - Installation: "installation.md"
  - Quickstart: "quickstart.md"
  - API Documentation:
      - Router: "api/router.md"
      - Transition: "api/transition.md"
      - ScreenBase: "api/screen.md"
      - ScreensFactoryBase: "api/factory.md"
      - ScreenPresenting: "api/presenter.md"
      - TransitionDirection: "api/direction.md"

extra_css:
  - "css/extra.css"

plugins:
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            members_order: source
            separate_signature: true
            show_symbol_type_heading: true
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: false
            line_length: 90
            show_signature_annotations: true

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
